apiVersion: v1
kind: ConfigMap
metadata:
  name: myworkflow-config
  namespace: namespace-workflow-1765396823478
  labels:
    app.kubernetes.io/name: myworkflow
    kubernetes.azure.com/generator: devhub
data: