apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myworkflow20
  labels:
    app.kubernetes.io/name: myworkflow20
    app.kubernetes.io/part-of: myworkflow20-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: myworkflow20