apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myworkflow
  labels:
    app.kubernetes.io/name: myworkflow
    app.kubernetes.io/part-of: myworkflow-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: myworkflow