apiVersion: v1
kind: Service
metadata:
  name: myworkflow
  namespace: namespace-workflow-1765396823478
  labels:
    app.kubernetes.io/name: myworkflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: myworkflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000