apiVersion: v1
kind: Service
metadata:
  name: myworkflow20
  namespace: namespace-workflow-1765416469520
  labels:
    app.kubernetes.io/name: myworkflow20
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: myworkflow20
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000